# Generated by Django 4.2.29 on 2026-03-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_publish_bb7600_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-id'], name='blog_post_id_821b27_idx'),
        ),
    ]
